### ISSUE TITLE
Auth not working

### ISSUE THREAD

**Issue by vexter0944** [mzashh/HUB75-Pixel-Art-Display#1]
I tried the default admin, admin in the code to auth - and I just get a 401.

I changed the password to password and still get 401.  Is there something about the auth I need to be aware of?

![image](https://github.com/mzashh/HUB75-Pixel-Art-Display/assets/23345472/1b7cff80-6b04-4489-b892-6e346b73d19b)

![image](https://github.com/mzashh/HUB75-Pixel-Art-Display/assets/23345472/3691e226-b3c5-40d9-8b5b-cf03373ae7c3)

**Comment by mzashh** [comment]
so you uploaded the code and went to the ip and its showing auth failed when you put the default username and password

**Comment by mzashh** [comment]
i'm pretty confused as to why its not working for you, try changing it in line 327 and 328

  config.httpuser = "admin";
  config.httppassword = "password";

also can you give some more information like ide version, hardware etc

**Comment by vexter0944** [comment]
Thanks for the response, appreciate it!  I'll try your suggestions and report back in.  Here's my arduino ide info:
![image](https://github.com/mzashh/HUB75-Pixel-Art-Display/assets/23345472/dd7d4e4f-ba55-4175-8492-c6acaa5fb110)

This is the esp32 I'm using: https://www.amazon.com/gp/product/B0718T232Z

IF you need more info - let me know.  I'll report back in as soon as I get a chance to try your suggestions as well.

**Comment by vexter0944** [comment]
Same issue if I change 327 and 328.  Still can't auth.  But yes, changing line 169 in webserver.ino to
bool isAuthenticated = true; worked and got me in.  I'm very puzzled as well.

**Comment by mzashh** [comment]
thats pretty odd, so lets see if we can get things matching
 
my IDE version is 1.8.19
async web server library version is 1.2.3

maybe try using these versions, other than the auth issue is everything working fine?

**Comment by vexter0944** [comment]
I can try 1.8.19.  I was just getting this up and running on the esp32 - have not wired up to hub75e panel yet, so not sure as to the display working fine yet.  I wanted to make sure it was functioning (uploads/webserver etc) - before doing all the hookup to the hub75e panel.  Will report in once hooked up to panel and confirmed working.  Thanks for your help and responsivness!

**Comment by pablomofo1** [comment]
Works perfect on legacy Adruino

**Comment by mzashh** [comment]
> Works perfect on legacy Arduino

Makes sense since i am also using legacy Arduino, so is everything working fine for you, webui, display etc

**Comment by mzashh** [comment]
Solution use legacy Arduino IDE, v1.8.19

**Comment by vexter0944** [comment]
Noted - thanks for the test and feedback, appreciate the help!
