### ISSUE TITLE
possible to use other resolution panels 

### ISSUE THREAD

**Issue by HungryBox45** [mzashh/HUB75-Pixel-Art-Display#3]
hello, i want to use a 64x32 panle with this firmware is it possible to do so?

**Comment by mzashh** [comment]
you can use any panel supported by the hub75 library, you just need to change the resolution and some initialisation code .

https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#supported-panels

**Comment by HungryBox45** [comment]
ok i will see, thank you
