### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by pablomofo1** [mzashh/HUB75-Pixel-Art-Display#5]
Can't get this to work anymore can you please help

**Comment by pablomofo1** [comment]
Might found my issue do I need to use version=2.0.7 of Library?

**Comment by mzashh** [comment]
specify more details about the issue, like what isnt working, is the display not initialising, is the code now compiling, is the web ui not working, also provide information about your hardware

**Comment by pablomofo1** [comment]
How can I change assigned pins

**Comment by pablomofo1** [comment]
Fixed my issue appreciate your work 👍

**Comment by pablomofo1** [comment]
You should link your fork Hub75 Library 2.0.7

**Comment by mzashh** [comment]
ok glad to hear that it fixed your issue.
Actually that is an older version of the library i have slightly modified, and it is linked in the firmware section under modified library.
To change the pin mapping refer to this https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA#2-wiring-the-esp32-to-an-led-matrix-panel
you can close the issue if its resolved
