### ISSUE TITLE
is it possible to use an TFT ili9341 display insted of  HUB75 ?

### ISSUE THREAD

**Issue by ajuniorps** [mzashh/HUB75-Pixel-Art-Display#6]
hello ! 
thanks for the project. im trying to use this project to upload gif files to my esp32-s3 and play on ili9341 3.2" display, is it possible ? 

sorry for my speech, English isn't my native language :)

**Comment by mzashh** [comment]
Hi there, This project is not suitable for TFT displays, to make it work you will need to add the TFT initialisation code, then port the GIF displaying function and then print it on the TFT. You can refer to this example from the AnimatedGIF library and then combine it with a Web Server and Web UI.

https://github.com/bitbank2/AnimatedGIF/tree/master/examples/TFT_eSPI_memory

Also kindly refrain from opening issues that are not directly related to this project, I won't be able to provide further support for issues outside the scope of this project.
