### ISSUE TITLE
LED-Ghosting

### ISSUE THREAD

**Issue by MasterChief1335** [mzashh/HUB75-Pixel-Art-Display#7]
Hi I have a problem when I make an image the edge should not light up

![PXL_20241029_055439346](https://github.com/user-attachments/assets/1a60e921-5905-404c-85e2-1fb0bd3f9ad6)

![PXL_20241029_055208544](https://github.com/user-attachments/assets/7911ac5c-2e77-42dd-8be9-613d4521e3fb)

**Comment by mzashh** [comment]
This does not seem to be an issue with the firmware. If you're experiencing ghosting, artifacts, or graphical glitches, this typically indicates either a wiring issue or a compatibility issue with your panel and the library. First, verify that your panel is compatible with the [ESP32-HUB75-MatrixPanel-DMA](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-DMA) library. You may need to adjust some initialization settings for proper functionality, refer to the library’s examples, documentation and issues for guidance. 

Ensure your panel displays images correctly, and once it does, replicate any code modifications you did to make it work in this code and it should hopefully work. If your panel displays images correctly and you are still having ghosting issues with this firmware you can reopen this issue.
