### ISSUE TITLE
Gif is not displayed 1:1

### ISSUE THREAD

**Issue by MasterChief1335** [mzashh/HUB75-Pixel-Art-Display#8]
I wanted to make a timer gif, the animation is played normally in Gimp but not on the display

![timerr](https://github.com/user-attachments/assets/efcc18e5-727c-4ffb-96a4-1fde6ae0c4b3)
Video
https://streamable.com/wji6lm

**Comment by mzashh** [comment]
To fix the GIF duration issue in `firmware.ino`, go to line 214 and change `if ((millis() - start_tick) > 8000)` to `if ((millis() - start_tick) > 50000)`. This will allow the GIF to play for up to 50 seconds.

**Comment by MasterChief1335** [comment]
can make 1 min?

**Comment by mzashh** [comment]
> can make 1 min?

Yes, just change 50000 to 60000. this indicates the time in ms so 60000 is 60 seconds so like this

`if ((millis() - start_tick) > 60000)`
